### ISSUE TITLE
docker-sync on mac does not sync everything

### ISSUE THREAD

**Issue by tienbuide** [spryker/docker-sdk#122]
Environment:
- macOS 10.15.5
- Docker version 19.03.8, build afacb8b
- docker-sync 0.5.14
- unison version 2.51.2 (ocaml 4.08.1)

use case:
we want to run grumphp on every pre-commit to check our requirements.
the grumphp looks kind of like that:

grumphp-config (minimized):
``` 
parameters:
    git_hook_variables:
        EXEC_GRUMPHP_COMMAND: docker/sdk cli php
    ignore_unstaged_changes: false
    process_timeout: 240
    tasks:
        composer:
            file: ./composer.json
        composer_script:
            script: "pre-commit"

        phplint:
        securitychecker:
            lockfile: ./composer.lock
        xmllint:
        yamllint:
```

this triggers `docker/sdk cli php vendor/phpro/grumphp/bin/grumphp run` before a commit is done (pre-commit-hook).
grumphp checks the `git diff --staged`.
unfortunately `docker-sync` does not sync the `.git/objects/<dir>` and thus grumphp cannot find the staged diff. 

example error message:
```
Error while running git command: 
 'git' '--git-dir' '/data/.git' '--work-tree' '/data' 'diff' '-r' '-p' '-m' 
 '-M' '--full-index' '--staged' 
 fatal: unable to read 60dd77cb9f169ebb7794bef497dd72d6640cfaab 
 diff --git a/.dockerignore b/.dockerignore 
 new file mode 100644 
 index 0000000000000000000000000000000000000000..4fae21fdea7a50536276eea0fa9
```

[1][https://github.com/phpro/grumphp](https://github.com/phpro/grumphp)
