### ISSUE TITLE
Key `sections` is not explained for installation recipes

### ISSUE THREAD

**Issue by localheinz** [spryker/docker-sdk#374]
I currently cannot find a documentation for the `sections` key of installation recipes.

How are we supposed to find out about

- what these sections are for
- what names we can use for sections
- what names we have to use for sections (e.g., `demodata`, see #373)

?

Running

```shell
git grep -i sections
```

on current `master` yields

```
bin/command/compose/up.sh:5:Registry::Help::command -c "up [--build] [--assets] [--data] [--jobs]" "Builds and runs Spryker applications based on demo data. Re-executes the sections specified as options even if they have been executed before."
context/php/php.ini:31:; special sections cannot be overridden by user-defined INI files or
context/php/php.ini:32:; at runtime. Currently, [PATH=] and [HOST=] sections only work under
context/php/php.ini:34:; http://php.net/ini.sections
docs/07-deploy-file/02-deploy.file.reference.v1.md:71:For example, Docker images, containers and volume names start with a `namespace:` to avoid intersections between different deployments on a single host machine.
docs/07-deploy-file/02-deploy.file.reference.v1.md:96:For example, Docker images and volumes are tagged with a `tag:` to avoid intersections between different boots for a signle deployment on a single host machine. The tag can be set directly in the deploy file to ensure that all the boots of a deployment run with the same images and volumes.
```

## Examples

See [`config/install/US/production.yml`](https://github.com/spryker-shop/b2b-demo-shop/blob/576d82c0c8d4e82e4de6c9169afbf26ba3e26f11/config/install/US/production.yml#L9-L33) from [`spryker-shop/b2b-demo-shop`](https://github.com/spryker-shop/b2b-demo-shop):

```yaml
sections:
    clean-oms:
        clear-oms-locks:
            command: "vendor/bin/console oms:clear-locks -vvv --no-ansi"

    diff:
        propel-migration-delete:
            command: "vendor/bin/console propel:migration:delete -vvv --no-ansi"

        propel-diff:
            command: "vendor/bin/console propel:diff -vvv --no-ansi"

        show_migrations:
            command: "ls -al ./src/Orm/Propel/Migration_*/*.php 2>/dev/null || true"

        propel-migrate:
            command: "vendor/bin/console propel:migrate -vvv --no-ansi"

        propel-migration-cleanup:
            command: "vendor/bin/console propel:migration:delete -vvv --no-ansi"

    scheduler-start:
        scheduler-setup:
            command: "vendor/bin/console scheduler:setup -vvv --no-ansi"
            stores: true
```

See [`config/install/docker.yml`](https://github.com/spryker-shop/b2b-demo-shop/blob/576d82c0c8d4e82e4de6c9169afbf26ba3e26f11/config/install/docker.yml#L4-L138) from [`spryker-shop/b2b-demo-shop`](https://github.com/spryker-shop/b2b-demo-shop):

```yaml
sections:
    build:
        generate-transfers:
            command: 'vendor/bin/console transfer:generate'

        router-cache-warmup-yves:
            command: 'vendor/bin/yves router:cache:warm-up'

        router-cache-warmup-backoffice:
            command: 'vendor/bin/console router:cache:warm-up:backoffice'

        router-cache-warmup-backend-gateway:
            command: 'vendor/bin/console router:cache:warm-up:backend-gateway'

        twig-cache-warmup:
            command: 'vendor/bin/console twig:cache:warmer'

        navigation-cache-warmup:
            command: 'vendor/bin/console navigation:build-cache'

        rest-request-validation-cache-warmup:
            command: 'vendor/bin/console rest-api:build-request-validation-cache'

        propel-copy-schema:
            command: 'vendor/bin/console propel:schema:copy'

        propel-build:
            command: 'vendor/bin/console propel:model:build'

        generate-entity-transfer:
            command: 'vendor/bin/console transfer:entity:generate'

        generate-page-source-map:
            command: 'vendor/bin/console search:setup:source-map'

        translator-generate-cache:
            command: 'vendor/bin/console translator:generate-cache'

    build-production:
        excluded: true
        cache-class-resolver-build:
            command: 'vendor/bin/console cache:class-resolver:build'

    build-development:
        generate-transfers:
            command: 'vendor/bin/console transfer:generate'

        generate-transfer-databuilders:
            command: 'vendor/bin/console transfer:databuilder:generate'

        generate-auto-completion:
            command: 'vendor/bin/console dev:ide-auto-completion:generate'

        rest-api-generate-documentation:
            command: 'vendor/bin/console rest-api:generate:documentation'

    build-static:
        dependencies-install:
            command: 'vendor/bin/console frontend:project:install-dependencies'

        yves-install-dependencies:
            command: 'vendor/bin/console frontend:yves:install-dependencies'

        zed-install-dependencies:
            command: 'vendor/bin/console frontend:zed:install-dependencies'

    build-static-production:
        excluded: true
        yves-build-frontend:
            command: 'vendor/bin/console frontend:yves:build -e production'

        zed-build-frontend:
            command: 'vendor/bin/console frontend:zed:build -e production'


    build-static-development:
        yves-build-frontend:
            command: 'vendor/bin/console frontend:yves:build'

        zed-build-frontend:
            command: 'vendor/bin/console frontend:zed:build'



    scheduler-setup:
        jenkins-setup:
            command: 'vendor/bin/console scheduler:setup'

    scheduler-suspend:
        excluded: true
        jenkins-suspend:
            command: 'vendor/bin/console scheduler:suspend'

    scheduler-clean:
        excluded: true
        jenkins-clean:
            command: 'vendor/bin/console scheduler:clean'

    init-storages-per-store:
        queue-setup:
            command: 'vendor/bin/console queue:setup'
        setup-search-create-sources:
            command: 'vendor/bin/console search:setup:sources'

    init-storages-per-region:
        propel-copy-schema:
            command: 'vendor/bin/console propel:schema:copy'

        propel-postgres-compatibility:
            command: 'vendor/bin/console propel:pg-sql-compat'

        propel-migration-delete:
            command: 'vendor/bin/console propel:migration:delete'

        propel-tables-drop:
            command: 'vendor/bin/console propel:tables:drop'

        propel-diff:
            command: 'vendor/bin/console propel:diff'

        propel-migrate:
            command: 'vendor/bin/console propel:migrate'

        propel-migration-cleanup:
            command: 'vendor/bin/console propel:migration:delete'

        init-database:
            command: 'vendor/bin/console setup:init-db'

    demodata:
        import-demodata:
            command: 'vendor/bin/console data:import --config=data/import/local/full_${SPRYKER_REGION}.yml'

        update-product-labels:
            command: 'vendor/bin/console product-label:relations:update'
```
