### ISSUE TITLE
Pass environment variables from host into SDK container

### ISSUE THREAD

**Issue by skrollme** [spryker/docker-sdk#532]
### What is the problem you are trying to solve by the feature?
I'm trying to pass a specific environment-variable from a host-machine into the docker-containers (primarily php) via image:environment section from the deploy-file. e.g.

```
...
environment: docker
pipeline: docker
image:
    tag: spryker/php:8.2-alpine3.18
    php:
        enabled-extensions:
            - blackfire
    environment:
        MY_VAR: $MY_VAR
...
```
This could be usefull to pass secrets during CI or other automated task to not hard-code them via config-files

### What is the solution you propose?
The declared variable contains the host-machine's value for this specific environment-variable or is at least able to passed via `MY_VAR=value docker/sdk up` or `MY_VAR=value docker/sdk cli`.

**OR**

Allow a custom .env file to be included in the docker-compose stack into all containers.

#### What changes in deploy.yml format do you propose?
Remove the forced quotation via single-quotes in [Dockerfile.twig](https://github.com/spryker/docker-sdk/blob/71652fd9eea8b80ac4fd5aeb06c6bb969e1b577c/images/common/application/Dockerfile.twig#L17)
```
...
{% for envName, envValue in _envs %}
ENV {{ envName }}='{{ envValue }}'
{% endfor %}
...
```

### What alternatives have you considered?
I did not came up any feasable alternative so far. All efforts to pass a variable were unsuccessfull. A `MY_VAR=value docker/sdk cli` also did not do the trick
